import React from "react"

export const LazyHome = React.lazy(() => import("../Home/home"))
export const LazyAbout = React.lazy(() => import("../About/about"))
export const LazyServices = React.lazy(() => import("../Services/service"))
export const LazyContact = React.lazy(() => import("../Contact/contact"))
export const LazyAuth = React.lazy(() => import("../Auth/auth"))
export const LazyProduct = React.lazy(() => import("../Product/product"))
export const LazyReset = React.lazy(() => import("../User/Reset/reset"))
export const LazyDashboard = React.lazy(() => import("../User/Dashboard/dashboard"))
export const LazyQuotation = React.lazy(() => import("../User/quotation/quotation"))
export const LazyLogistics = React.lazy(() => import("../Home/Service/ServicePages/Logistics/Logistics"))
export const LazyStorage = React.lazy(() => import("../Home/Service/ServicePages/Storage/Storage"))
export const LazyBrokerage = React.lazy(() => import("../Home/Service/ServicePages/Brokerage/Brokerage"))
export const LazyAir = React.lazy(() => import("../Home/Service/ServicePages/Air/Air"))
export const LazyLinkages = React.lazy(() => import("../Home/Service/ServicePages/Linkages/Linkages"))
export const LazyAdvisory = React.lazy(() => import("../Home/Service/ServicePages/Advisory/Advisory"))
export const LazyServiceType = React.lazy(() => import("../Forms/ServiceQuotation/ServiceType/ServiceType"))
export const LazyOcean = React.lazy(() => import("../Home/Service/ServicePages/Ocean/Ocean"))
export const LazyRefining = React.lazy(() => import("../Home/Service/ServicePages/Refining/Refining"))
export const LazyProductQuotation = React.lazy(() => import("../Forms/ProductQuotation/ProductQuotation"))
export const LazyShipment = React.lazy(() => import("../shipment/shipment"))
export const LazyLogisticsQuotation = React.lazy(() => import("../Forms/LogisticsQuotation/LogisticsQuotation"))
export const LazyServiceQuotation = React.lazy(() => import("../Forms/ServiceQuotation/ServiceQuotation"))
export const LazyStorageTable = React.lazy(() => import("../shipment//shipmentTable/StorageTable/StorageTable"))
export const LazyShipmentTable = React.lazy(() => import("../shipment/shipmentTable/ShipmentDataTable/ShipmentTable"))
export const LazyNotFound = React.lazy(() => import("../404/404"))